### ISSUE TITLE
NGCC-SOEC Model Optimization Results Minor Difference

### ISSUE THREAD

**Issue by eslickj** [IDAES/examples#11]
There is a minor difference in the results from the latest NGCC-SOEC example notebook.  Looking at cell 13, the Fixed O&M cost come out to be 74.9 and was expected to be 74.6.  The annualized total as spent cost comes out to be 150.5 but is expected to be 150.1.  I don't think is a really significant difference.  It could be related to changes to the core framework or costing framework, but I don't think I have much hope of pinpointing the issue.  I'm just going to recommend changing the reletive tolerance in cell 13 to 1e-2.

**Comment by bpaul4** [comment]
@eslickj the differences are probably related to recent and ongoing changes to the costing framework. I agree with your recommendation to lower the tolerance, once the framework is finalized we can revisit the notebook and tighten the checks if desired.
