### ISSUE TITLE
Initial tutorial loads with no solver

### ISSUE THREAD

**Issue by TimBartholomew** [IDAES/examples#115]
When opening the introductory tutorials on the webpage, they load with an error stating they can't find the solver.

For both:

- [Introduction to IDAES](https://idaes-examples.readthedocs.io/en/latest/docs/tut/introduction_short_doc.html)
- [Introduction to IDAES (short)](https://idaes-examples.readthedocs.io/en/latest/docs/tut/introduction_doc.html)

See below:
![image](https://github.com/IDAES/idaes-pse/assets/25497093/c610df23-7c72-498e-a705-da4a8dc0226b)

**Comment by andrewlee94** [comment]
Do we even need to keep these tests around? They wee intended to be an easy way to debug issues when we ran the tutorial in person, but they have not been maintained since then.

**Comment by andrewlee94** [comment]
It looks like this issue is more wide spread however, as this error is showing up in the other examples too: e.g. https://idaes-examples.readthedocs.io/en/latest/docs/tut/core/flash_unit_doc.html

**Comment by andrewlee94** [comment]
Also, I am not sure if it is just me, but I looked at the HDA tutorial and the formatting was really messed up (to the point of being unreadable): https://idaes-examples.readthedocs.io/en/latest/docs/tut/core/hda_flowsheet_doc.html
