### ISSUE TITLE
TypeError: metaclass conflict in examples 

### ISSUE THREAD

**Issue by elizabethkeith** [IDAES/examples#125]
When working through the examples, in the blocks that create the model and flowsheet, this error happens:

<img width="1115" alt="Screenshot 2024-06-19 at 8 28 41 AM" src="https://github.com/IDAES/examples/assets/113551905/e0391ae7-f806-4fc2-96da-d02a17e3b863">

I've tried both the flash unit example and the HDA flowsheet example, and the error occurs on both.

**Comment by andrewlee94** [comment]
Related to https://github.com/IDAES/idaes-pse/discussions/1435
