### ISSUE TITLE
Ensure Black formatting

### ISSUE THREAD

**Issue by lbianchi-lbl** [IDAES/examples#133]
While working on #128, I realized that even though `black` is part of the dev dependencies:

1) There's no check enforced by the CI
2) The codebase (or at least a large portion of it) has not been formatted with Black (i.e. if one runs `black .`, 171 files are reformatted)

Before the upcoming release, we should:

- [ ] Update the Black version in `requirements-dev.txt` to match the one used in `idaes-pse`
- [ ] Add a Black formatting check to the CI
- [ ] Run `black .` on the entire repository (including Jupyter notebooks)

**Comment by bpaul4** [comment]
@lbianchi-lbl I think this is a great idea, however I'm wary of what `black` will do to JSON-like code in `.ipynb` files. Let me know if I can assist with this effort at all.
