### ISSUE TITLE
Fix 'held' notebook for HDA

### ISSUE THREAD

**Issue by dangunter** [IDAES/examples#20]
https://github.com/IDAES/examples/blob/main/idaes_examples/notebooks/held/flowsheets/hda_flowsheet_with_distillation_src.ipynb

Offending cell (at bottom):
```
import pytest

print(value(m.fs.operating_cost))
print(value(m.fs.capital_cost))

assert value(m.fs.operating_cost) == pytest.approx(408342.352, abs=100)
assert value(m.fs.capital_cost) == pytest.approx(29926.759, abs=100)
```
Assertion error with printed output:
```
408883.53148307273
29956.366943197827
```

**Comment by bpaul4** [comment]
I updated to the most recent commit status on `idaes-pse`, and ran this notebook both in my local `examples-pse` and after installing the new `examples` repository. I obtained the output below:

`408261.6274962933
29919.158819973974`

These values are within the error tolerance specified - @dangunter would it be convenient to re-check this example and if needed upload the new output to this repository?

**Comment by dangunter** [comment]
The expected fix to this issue is a PR that moves the notebook from 'held' to the appropriate directory, updating the table of contents appropriately, and which then passes tests.

**Comment by andrewlee94** [comment]
@bpaul4 Any updates on addressing these fixes?

**Comment by lbianchi-lbl** [comment]
No updates as of now, @bpaul4 will look into it in the coming days.

**Comment by lbianchi-lbl** [comment]
We need to get the infrastructure sorted out (#44, #42, etc) before work can resume on this.
