### ISSUE TITLE
Fix 'held' notebook ngcc_soec

### ISSUE THREAD

**Issue by dangunter** [IDAES/examples#22]
Last error was timing out on a solve, but that may be a symptom of a bigger issue. Probably need John E.'s help on this one.

**Comment by eslickj** [comment]
I think we can remove this notebook.  We just need to keep the NGCC, but don't need the NGCC+SOEC.  So you can remove:
* ngcc_soec*
* soec_*

in the ngcc directory

**Comment by dangunter** [comment]
@eslickj Should this one be removed then?

**Comment by eslickj** [comment]
@dangunter, yeah just the soec related stuff listed.  There is also a plain NGCC model in that directory that we should keep.
