### ISSUE TITLE
Setup fails on ARM64 macOS due to default `tensorflow` requirement

### ISSUE THREAD

**Issue by eslickj** [IDAES/examples#31]
When I run setup I get an error that there is no package "tensorflow" available.  I'm not totally sure, but I assume this is because I'm using a Mac with an ARM64 processor.  Removing tensorflow from the requirements let me install examples successfully.

**Comment by andrewlee94** [comment]
If possible, it would also be good to make `tensorflow` an optional dependency. It is only needed for the Keras/OMLT example and is a fairly large download.

**Comment by lbianchi-lbl** [comment]
This can be part of the changes to the `idaes-examples` dependencies reorg that I'm working on (related to IDAES/idaes-pse#705).

**Comment by ksbeattie** [comment]
Related to #26
