### ISSUE TITLE
Possible improvements to current naming scheme

### ISSUE THREAD

**Issue by lbianchi-lbl** [IDAES/examples#51]
While there's no urgent need to do so, we have discussed the possibility of considering alternatives to the naming scheme (and consequently notebook discovery and processing logic) currently being used.

Unless (or until) there are concrete plans to actually change something, the purpose of this issue is to brainstorm, collect, and document the various solutions being considered and their pros/cons evaluations.

**Comment by lbianchi-lbl** [comment]
To start things off: one disadvantage of the current scheme (based on the `_src` path stem prefix) is due to accidental "collisions" occurring if the `snake_case` path stem happens to contain a word that is lexically sorted somewhere between the set of suffixes being used.

In this example, the notebook having `introduction_short` as its path stem is sorted before the `_src`-suffixed version of the `introduction` notebook, preventing the set of related suffixed notebook files from being grouped together:

![image](https://github.com/IDAES/examples/assets/48035537/af888748-8c23-4186-af65-8e84dc994435)

**Comment by dangunter** [comment]
The removal of the '_src' suffix has been implemented. @lbianchi-lbl I think we can close this issue now
