### ISSUE TITLE
Formulas not rendered correctly in Custom Compressor Unit Model notebook (and possibly others as well)

### ISSUE THREAD

**Issue by lbianchi-lbl** [IDAES/examples#63]
https://idaes-examples.readthedocs.io/en/latest/docs/unit_models/custom_unit_models/custom_compressor_doc.html

![image](https://github.com/IDAES/examples/assets/48035537/08bea2a5-cbff-4527-ae21-8541e370ab71)

**Comment by olawale0254** [comment]
Hello there 👋🏻.
Can I work on this?
