### ISSUE TITLE
Update FS visualizer tutorial to track changes in IDAES UI code

### ISSUE THREAD

**Issue by lbianchi-lbl** [IDAES/examples#68]
Related to:

- IDAES/idaes-pse#1146

---

- [ ] Links in "Further reading" section should be updated to point to the current/proper location of the UI docs
- [ ] The function `quiet()` from `idaes_examples.mod.tut.visualizer_tutorial` also disables the warning emitted by `idaes.core.base.flowsheet_model.visualize()` if the IDAES UI code is not installed/available.

**Comment by dangunter** [comment]
@lbianchi-lbl note started a PR for this
